### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ezar** [Tueti/MMM-MovieListings#4]
Crash MagicMirror every time I use it :(

**Comment by Tueti** [comment]
Could you give a bit more insight, please? It's the first time I hear about this.
- What is your configuration for this module?
- Did you try without any other module to verify it actually is caused by this one?
- Did you do any other configuration on your system?

I hope we can fix the issue, though!

**Comment by ezar** [comment]
Sorry, it's my fault... The problem is watchdog plugin :(
Thanks!
